# Schema for the configuration files of the d8_night module.

d8_night.settings:
  type: config_object
  label: 'D8+ Night settings'
  mapping:
    cdn_theme:
      type: string
      label: 'Bootstrap CDN theme for dark mode'
