name: D8+ Feature Settings
description: Provides some configuration.
package: D8+

type: module
core_version_requirement: ^10

lifecycle: deprecated
lifecycle_link: https://github.com/lexhouk/d8/issues/288
