name: 'D8+ Config Export to PHP array'
type: module
description: 'Provides a wrapper for the "Config Export to PHP array" module.'
core_version_requirement: ^9
package: 'D8+'
dependencies:
  - config2php:config2php
