name: 'D8+ Config Export to PHP array'
type: module
description: 'Provides a wrapper for the "Config Export to PHP array" module.'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'D8+'
dependencies:
  - config2php:config2php
